baseurl = "precious-fox-65ec42.netlify.app"
theme = "hugo-creative-portfolio-theme"
title = "Muadh Monsur"

languageCode = "en-us"
# Enable comments by entering your Disqus shortname
disqusShortname = ""
# Enable Google Analytics by entering your tracking code
googleAnalytics = ""

[params]
  # Style options: defa (pink), blue, green, pink, red, sea, violet

  # Use custom.css for your custom styling
  style = "pink"
  description = "This is a collection of my web development works so far"
  copyright = "&copy;2023 MUADH"
  sidebarAbout = [
    "Hi There ğŸ‘‹, I'm Muadh Monsur",
    "Based in Osogbo, Nigeria.ğŸŒ",
    "A Student of Fountain University. ğŸ«"
  ]
  

  # Nav links in the side bar
  [[params.navlinks]]
  name = "Home"
  url = "portfolio/"
  home = true

  [[params.navlinks]]
  name = "About"
  url = "about/"


  [params.social]
  email         = "muadh117a@gmail.com"
  github        = "https://github.com/A2ITNotes"
  youtube       = "https://www.youtube.com/channel/UC7UC2xLBV9IHYdNm9s8TQXA"
  whatsapp      = "wa.me service link"
